Avoid creating new view ids for reused frame buffers
BabylonJS/BabylonNative pull request #436
Opened 2020-10-05 23:18 UTC by rgerd

This PR:

1) Keeps us from unnecessarily creating new views whenever frame buffers are re-bound or the viewport is set.

2) Properly sets the default back buffer frame buffer view id to 0 to conventionally correspond with bgfx's use of 0 as the default back buffer view id.

2) Fixes bug #387, re-adding the call to `bgfx::touch` so that bgfx properly clears the view even when no geometry is submitted to the view for rendering. 

3) Fixes an issue where we were clearing the view as a side-effect of setting the viewport. Because Babylon.js does not unbind the frame buffer to which the scene was last rendered, the left eye was getting clipped by a call to setViewport at the beginning of the right eye being rendered. On top of this, the size of the view rect created by setViewport always corresponded to the size of the default back buffer (defined by `bgfx::getStats()->[width/height]()`), and not to the currently bound back buffer. [See here for a discussion of this issue on the Babylon.js forum.](https://forum.babylonjs.com/t/bound-active-camera-frame-buffer-not-unbound-in-scene-render/14559)

2020-10-06 18:33 UTC, syntheticmagus requested changes
I think there's more going on here than meets the eye. The main thing that jumps out at me is that we probably need to be able to "recycle" view IDs one way or another so that long-running apps that spawn many views (among other scenarios) won't run out. That was what the old `RecycleSet` was for, but we specifically [got rid of the `RecycleSet`](https://github.com/BabylonJS/BabylonNative/pull/86/files) during a fix for some broken behavior that had to do with the validation tests. (I wonder if this has something to do with the current validation test failures, too?) I don't fully remember what exactly was broken that was fixed by #86, but it's probably worth checking into since this change seems to be targeting a shift back toward the sort of state-preserving architecture that we consciously made "a clean break from" when we adopted the current approach. Perhaps @CedricGuillemet remembers more about the context for this?

2020-10-06 18:33 UTC, syntheticmagus commented on Plugins/NativeEngine/Source/NativeEngine.cpp
> -                GetFrameBufferManager().Reset();
Without a reset or a recycling mechanism, the view IDs will increase without bound over time, eventually exceeding `bgfx::getCaps()->limits.maxViews`, right? Or is there another mechanism preventing this from happening?

2020-10-06 18:33 UTC, syntheticmagus commented on Plugins/NativeEngine/Source/NativeEngine.h
> +            m_boundFrameBuffer = m_defaultBackBuffer = new FrameBufferData(BGFX_INVALID_HANDLE, 0, bgfx::getStats()->width, bgfx::getStats()->height);
Is this a behavior change from the way it worked before? If so, do we know why it used to be different?

2020-10-06 18:33 UTC, syntheticmagus commented on Plugins/NativeEngine/Source/NativeEngine.h
> +            const auto viewId = isNewFrameBuffer ? GetNewViewId() : m_boundFrameBuffer->ViewId;
Why do this here and not at `FrameBufferData`'s creation time? The check on 255 is a bit odd.

2020-10-06 20:36 UTC, rgerd commented
@syntheticmagus The PR you linked cleared some stuff up for me. I led myself into a false assumption after our earlier conversation that we wanted view id's to persist permanently, but now I see that my original read was more correct-- that we are trying to have view id's persist per-frame only. 

Please correct me if I'm wrong, but reassigning the view id's on bind and setViewport seems to be our method for reassigning view id's per-frame, but since Babylon.js could call setViewport multiple times on the same bound framebuffer per-frame, it seems like we need to actually just reassign per-frame.

I'm currently rolling back most of my changes to see if I can drive reassignment off of calls to `frameBufferManager->Reset()` (which is called at the end of each frame) and preserve most of the original core logic, which was correct the first time around.

I'll get this right eventually 👀

2020-10-28 18:45 UTC, rgerd commented
Going to rebase on the new threading changes and put up a fresh PR.

2020-10-28 18:45 UTC, closed without merging